require("prototypes.lava-drill.entity")
require("prototypes.lava-drill.item")
require("prototypes.lava-drill.recipe")
require("prototypes.lava-drill.technology")
require("prototypes.magma-ore.resource")
require("prototypes.magma-ore.item")